### Post request to example server
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "John Doe",
  "email": "abcd@example.com",
  "address": "123 main street",
  "dateOfBirth": "1995-02-01",
  "registeredDate": "2004-11-28"
}
###